swagger: "2.0"
info:
  version: 1.0.0
  title: "Taproom"
  description: A beer menu API
  termsOfService: http://swagger.io/terms/
  contact:
    name: Apiary
    email: support@apiary.io
    url: http://apiary.io
  license:
    name: MIT
    url: http://github.com/gruntjs/grunt/blob/master/LICENSE-MIT
host: localhost:3000
basePath: /
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /beers:
    get:
      description: Returns a list of beers!
      responses:
        200:
          description: succesful beer response
          headers:
            Content-Type:   
              type: string
              default: application/json; charset=utf-8
          schema:
            type: array
            items:
              $ref: '#/definitions/Beer'
definitions:
  Beer:
    allOf:
      - $ref: '#/definitions/NewBeer'
      - required:
        - id
        properties:
          id:
            type: string
            
  NewBeer:
    required:
      - name
      - type
    properties:
      name:
        type: string
      type:
        type: string
